### ISSUE TITLE
Support for ETC1-flavored .anb files?

### ISSUE THREAD

**Issue by applecuckoo** [meh2481/wfLZEx#12]
@meh2481 Hi! I'm currently working on ripping a couple of LeapFrog games that were developed by WayForward. The .anb files seem to have the same structures as the known working files, although they don't actually decode right since WF used a different type of image compression (probably ETC1). Same for the .tex files. If you're still interested, I've attached the contents of one of the .pak files for you to have a look at. Thank you!

[global.zip](https://github.com/user-attachments/files/17878199/global.zip)

**Comment by meh2481** [comment]
![fx_dust_poof](https://github.com/user-attachments/assets/05c917f5-319b-4f2b-9dae-6c6bb079309c)
![hazards](https://github.com/user-attachments/assets/b2ed8af0-72f4-44f2-8deb-6165c883c396)
![beetle_portrait](https://github.com/user-attachments/assets/0db6b860-c45b-4eca-b1f4-d56ebab7ffa1)
![cirriculum](https://github.com/user-attachments/assets/7d673115-0436-46dd-bbe1-bca1f405beb3)
![cutscene](https://github.com/user-attachments/assets/f8b49f78-5669-4a83-9156-1fc5cb77a346)
![docock_portrait](https://github.com/user-attachments/assets/966c4761-6283-4a03-bb8c-4d3ff465e045)
![electro_portrait](https://github.com/user-attachments/assets/12554344-bff8-4340-a643-53187b6a0cb4)
![fury_portrait](https://github.com/user-attachments/assets/1f4b92d4-1f19-461a-8808-4c9715a6f349)
![fury_right_portrait](https://github.com/user-attachments/assets/66c34835-8f46-4d02-9d2d-10e7742c359d)


Ran some cursory tests and it does look like ETC compression; they messed with their texture header type field, so it's not possible to have a program that supports both old and new .anb formats. One of the texture types (2 in the texture type field in the header) looks to just be ETC and decompresses just fine (evidenced by the spiderman image in cutscene.anb and cirriculum.anb). Texture type 3 seems messed up; not sure what's going on there. Might even be the wrong color; I'm not sure Nick Fury is supposed to be blue. I've pushed up my testing so far to the "etc" branch here. I might not work on this again but it should serve as a good starting point if someone else wants to.

**Comment by applecuckoo** [comment]
Thank you! Texture type 3 only looks wrong because the red and blue channels are swapped. Also, not sure if you saw, but there are some .tex files lying around in that global folder. I tried your old shantae_tex converter on those and it looks like they also use ETC1 - I'm not sure if you're up to it, but it would be great if you could spin up an ETC1 version of that as well.

**Comment by meh2481** [comment]
The code is open-source and pull requests are welcome. As I said above, I am not actively working on this project.

**Comment by applecuckoo** [comment]
Ah, okay. Could you open source the .tex tool? It looks like the code for it isn't here. That's the only thing left, so I'm closing this issue.

**Comment by meh2481** [comment]
Unfortunately I think I lost the code for tex_decompress somewhere along the way. It's pretty simple, though; it's just the texHeader section of the .anb without any of the jigsaw image recombining stuff.
