### ISSUE TITLE
wfLZEx

### ISSUE THREAD

**Issue by darksonicyozhik** [meh2481/wfLZEx#4]
Hello!

I'm the administrator "FaN&C" Family's Team.
We madding games into the Russian Language.

We can't compress/decompress ANB-format with wfLZ-format files.

The Game: Shantae Half-Genie Hero Complete Edition.

Your program decompresses ANB into PNG, but can't compress PNG into ANB.

Can you make a program for compress ANB?

We really need your help!

With respect,
DarkSonicYozhik

**Comment by meh2481** [comment]
You closed this, but for future reference/anyone else searching: No, going PNG->ANB is very nontrivial. There's a lot of unknown fields and data in the file format, and those presumably would all have to be reverse-engineered and filled out before recompression is possible. It might be possible to leave some resources untouched and just repack them while modifying others, but there's potential problems cross-linking resources. Neither of these options really appeal to me; I was more interested in extracting images than compressing them (The "Ex" in the repo name is for "Extract"). 
I'm pretty much done with the format/program until Shantae 5 is released. PRs are of course welcome, and I'll try to get to them in a timely manner.

**Comment by leamsii** [comment]
I wrote a script that handles PNG->ANB but in all honesty it was hell. 90% of the data is unknown, I only swapped out the image values leaving everything else intact.
